### ISSUE TITLE
Add wildcard support for friendly role names

### ISSUE THREAD

**Issue by joshgch** [okta/okta-aws-cli#123]
My organization has a consistent role-naming policy across several accounts. It would be great to support wildcards in place of the account ID in the ARN so that this:
```yaml
awscli:
  roles:
    "arn:aws:iam::123456789012:role/admin": "Prod Admin"
    "arn:aws:iam::123456789012:role/operator": "Prod Ops"
    "arn:aws:iam::012345678901:role/admin": "Dev Admin"
    "arn:aws:iam::012345678901:role/operator": "Dev Ops"
 ```

Would become this:
```yaml
awscli:
  roles:
    "arn:aws:iam::*:role/admin": "Admin"
    "arn:aws:iam::*:role/operator": "Ops"
 ```

This would simplify the yaml file and make logging in easier for my team.
