### ISSUE TITLE
Idp defined in yaml is not being selected for use 

### ISSUE THREAD

**Issue by pdubb29** [okta/okta-aws-cli#228]
V2.3.0 requires me to set a value when I've already provided the idp in the yaml file.
 
the flag `--aws-iam-idp` is not respected as defined in the documentation.
![image](https://github.com/user-attachments/assets/e8736e54-71d9-4bc7-8517-9ed29968e5e2)

 
WARNING: okta.yaml missing "awscli.idps" section
 
example okta.yaml:
``` 
awscli:
  profiles:
    sandbox:
      oidc-client-id: "**REDACTED**"
      org-domain: "**REDACTED**"
      aws-iam-idp: "arn:aws:iam::**REDACTED**"
      write-aws-credentials: true
      open-browser: true
      session-duration: 36000
```

Expected Result:
`okta-aws-cli -e -p sandbox` should not ask me for an idp.
